Release v1.0.0
gongled/vgrepo pull request #2
Opened 2017-05-17 13:34 UTC by gongled

Please have a look at my first software on Go programming language.

2017-05-17 13:44 UTC, andyone requested changes

2017-05-17 13:44 UTC, andyone commented on Makefile
> +	git config --global http.https://gopkg.in.followRedirects true
gopkg.in is not used in project. Try to generate actual makefile with [gomakegen](https://github.com/essentialkaos/gomakegen).

2017-05-17 13:44 UTC, andyone commented on cli/cli.go
> +		fmtc.Printf("{r}Unknown command{!}\n")
Use `terminal. PrintErrorMessage` which will print error message to stderr. `fmtc.Printf` output data to `stdout`.

2017-05-17 13:44 UTC, andyone commented on cli/cli.go
> +	info.AddCommand(CMD_ADD, "Add image to the Vagrant repository")
Add command arguments to command info like this:
```
info.AddCommand(CMD_ADD, "Add image to the Vagrant repository", "name", "version")
```

ek.usage also support optional command arguments. If you want to mark arguments as optional, just add `?` prefix to name, like this:
```
info.AddCommand(CMD_ADD, "Add image to the Vagrant repository", "?name", "?version")
```

2017-05-17 13:44 UTC, andyone commented on cli/cli.go
> +		err = fmtc.Errorf("Unable to handle %v arguments\n", len(args))
Do not append new line symbols to error message.

2017-05-17 13:44 UTC, andyone commented on cli/cli.go
> +		var name = args[0]
You can simplify this line to:
```
name := args[0]
```

Or just print it:
```
fmtc.Println(args[0])
```

2017-05-17 13:57 UTC, andyone requested changes

2017-05-17 13:57 UTC, andyone commented on prefs/prefs.go
> +	"os"
Separate imports from different sources, like this:
```
import (
  "os"

  "pkg.re/essentialkaos/ek.v8/knf"
  "pkg.re/essentialkaos/ek.v8/fmtc"
}
```

2017-05-17 13:57 UTC, andyone commented on prefs/prefs.go
> +	StorageURL string
Looks like this code is not well formatted. Use `make fmt` before commit.

2017-05-17 13:57 UTC, andyone commented on prefs/prefs.go
> +		fmtc.Printf(err.Error())
Try to avoid printing errors or warnings outside of cli. Return error text as error struct, and print it in CLI.

2017-05-17 13:57 UTC, andyone commented on prefs/prefs.go
> +	return p
`p` is useless here. Create and return struct in same time, like this:
```
return &Preferences{
 		StorageURL: knf.GetS(STORAGE_URL),
 		StoragePath: knf.GetS(STORAGE_PATH),
 	}
```

Also you can use simplified syntax for structure creation:
```
&Preferences{knf.GetS(STORAGE_URL), knf.GetS(STORAGE_PATH)}
```

In this case you should define struct variables in same order as they are defined in struct.

2017-05-17 13:57 UTC, andyone commented on prefs/prefs.go
> +		StorageURL: cnf.GetS(STORAGE_URL),
Typo, package name is `knf`.

2017-05-17 13:57 UTC, andyone commented on vgrepo.knf
> +  url: http://localhost:8080
Add comments about each property here. knf format used `#` symbol as comments prefix:
```
# Repository URL and port
url: http://localhost:8080
```

2017-05-17 13:57 UTC, andyone commented on meta/meta.go
> +	err := jsonutil.EncodeToFile(metaPath, m)
`err` is useless here. Just return error from `EncodeToFile`:
```
return jsonutil.EncodeToFile(metaPath, m)
```

2017-05-17 14:02 UTC, andyone commented on Makefile
> +	go get -d -v pkg.re/essentialkaos/ek
This is looks strange. This record means that you use somewhere ek import without version.

2017-05-17 14:03 UTC, andyone commented on Makefile
> +# gomakegen --output Makefile .
`Makefile` is default output file in gomakegen. You can execute gomakegen without any options.

2017-05-17 19:21 UTC, gongled commented on Makefile
> +# gomakegen --output Makefile .
Thank. Fixed (cffd47221421fb6c16f5e74fb471395ef424a479).

2017-05-17 19:21 UTC, gongled commented on Makefile
> +	go get -d -v pkg.re/essentialkaos/ek
I found and fixed typo in import section (cffd47221421fb6c16f5e74fb471395ef424a479).

2017-05-17 19:23 UTC, gongled commented on meta/meta.go
> +	err := jsonutil.EncodeToFile(metaPath, m)
Removed unnecessary variable assignment (cffd47221421fb6c16f5e74fb471395ef424a479).

2017-05-17 19:23 UTC, gongled commented on vgrepo.knf
> +  url: http://localhost:8080
Good advice. I added comment blocks to the sample configuration file. Done.

2017-05-17 19:24 UTC, gongled commented on prefs/prefs.go
> +	return p
Removed unnecessary `Preferences` struct. It is not relevant anymore.

2017-05-17 19:24 UTC, gongled commented on prefs/prefs.go
> +		StorageURL: cnf.GetS(STORAGE_URL),
Removed unnecessary `Preferences` struct. It is not relevant anymore.

2017-05-17 19:24 UTC, gongled commented on prefs/prefs.go
> +		fmtc.Printf(err.Error())
Removed unnecessary `Preferences` struct. It is not relevant anymore.

2017-05-17 19:27 UTC, gongled commented on prefs/prefs.go
> +	StorageURL string
Thanks. I added `make fmt` and `gomakegen` commands to the pre-commit hook. I suppose now there is no chance to forgot to format and generate Makefile properly.

2017-05-17 19:29 UTC, gongled commented on prefs/prefs.go
> +	"os"
I have trying to organize imports somehow, but IDEA (Gogland) sometimes changes an order of import automatically. Right now it looks fine.

2017-05-17 19:30 UTC, gongled commented on cli/cli.go
> +	info.AddCommand(CMD_ADD, "Add image to the Vagrant repository")
Nice tip. Done (cffd47221421fb6c16f5e74fb471395ef424a479).

2017-05-17 19:33 UTC, gongled commented on cli/cli.go
> +		err = fmtc.Errorf("Unable to handle %v arguments\n", len(args))
Done.

2017-05-17 19:33 UTC, gongled commented on cli/cli.go
> +		var name = args[0]
Fixed.

2017-05-17 19:33 UTC, gongled commented on Makefile
> +	git config --global http.https://gopkg.in.followRedirects true
Done.

2017-05-17 19:34 UTC, gongled commented on cli/cli.go
> +		fmtc.Printf("{r}Unknown command{!}\n")
Thanks. Nice tip.

2017-05-17 20:24 UTC, andyone commented on meta/meta.go
> +	return &clone
This code doesn't clone (_deep copy_) original struct - https://play.golang.org/p/4_J9g1iYpp
You should use [reflect](https://golang.org/pkg/reflect/) package for this.

2017-05-18 20:42 UTC, andyone commented on meta/meta.go
> +	return first.Less(second)
You can replace manual version parsing and comparison by [`VersionCompare`](https://godoc.org/pkg.re/essentialkaos/ek.v9/sortutil#VersionCompare) method from `sortutil` package.

2017-05-19 21:16 UTC, andyone commented on meta/meta.go
> +	return fmtc.Sprintf("%s/%s/%s/%s",
Use `fmt` package instead of `fmtc` here. `fmtc` _always_ try to find formatting tags in input and convert it to escape characters.

2017-05-23 20:56 UTC, gongled commented
@andyone would you mind to review this PR once again?

2017-05-24 18:21 UTC, merged